[2025-05-16T07:05:44.444+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-16T07:05:44.454+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-16T07:05:43.359538+00:00 [queued]>
[2025-05-16T07:05:44.458+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-16T07:05:43.359538+00:00 [queued]>
[2025-05-16T07:05:44.459+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-16T07:05:44.466+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): tiktok_videos_scraper_task> on 2025-05-16 07:05:43.359538+00:00
[2025-05-16T07:05:44.468+0000] {standard_task_runner.py:72} INFO - Started process 10044 to run task
[2025-05-16T07:05:44.471+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper_task', 'manual__2025-05-16T07:05:43.359538+00:00', '--job-id', '6096', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmph8747ydx']
[2025-05-16T07:05:44.472+0000] {standard_task_runner.py:105} INFO - Job 6096: Subtask tiktok_videos_scraper_task
[2025-05-16T07:05:44.511+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-16T07:05:43.359538+00:00 [running]> on host 8579eb2523da
[2025-05-16T07:05:44.563+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T07:05:43.359538+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T07:05:43.359538+00:00'
[2025-05-16T07:05:44.563+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-16T07:08:45.723+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-16T07:08:45.724+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-16T07:08:45.725+0000] {process_utils.py:132} INFO - Sending 15 to group 10044. PIDs of all processes in the group: [10047, 10059, 10066, 10067, 10090, 10104, 10156, 10157, 10196, 10409, 10044]
[2025-05-16T07:08:45.725+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 10044
[2025-05-16T07:08:45.726+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-16T07:08:45.733+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10157, status='terminated', started='07:05:45') (10157) terminated with exit code None
[2025-05-16T07:08:45.829+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10156, status='terminated', started='07:05:45') (10156) terminated with exit code None
[2025-05-16T07:08:45.829+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10409, status='terminated', started='07:08:45') (10409) terminated with exit code None
[2025-05-16T07:08:45.830+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10059, status='terminated', started='07:05:45') (10059) terminated with exit code None
[2025-05-16T07:08:45.830+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10196, status='terminated', started='07:05:45') (10196) terminated with exit code None
[2025-05-16T07:08:45.830+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10066, status='terminated', started='07:05:45') (10066) terminated with exit code None
[2025-05-16T07:08:45.830+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10104, status='terminated', started='07:05:45') (10104) terminated with exit code None
[2025-05-16T07:08:45.831+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10067, status='terminated', started='07:05:45') (10067) terminated with exit code None
[2025-05-16T07:08:45.831+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10090, status='terminated', started='07:05:45') (10090) terminated with exit code None
[2025-05-16T07:09:43.251+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=10047, name='node', status='sleeping', started='07:05:44') did not respond to SIGTERM. Trying SIGKILL
[2025-05-16T07:09:43.255+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=10044, name='airflow task ru', status='sleeping', started='07:05:44') did not respond to SIGTERM. Trying SIGKILL
[2025-05-16T07:09:43.255+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 10044
[2025-05-16T07:09:43.264+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10044, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='07:05:44') (10044) terminated with exit code -9
[2025-05-16T07:09:43.264+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=10047, name='node', status='terminated', started='07:05:44') (10047) terminated with exit code None
[2025-05-16T07:09:43.264+0000] {standard_task_runner.py:190} ERROR - ('Job 6096 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
